# Auto-label pull requests based on changed files
frontend:
  - changed-files:
      - any-glob-to-any-file: ["src/**", "public/**"]

ci:
  - changed-files:
      - any-glob-to-any-file: [".github/workflows/**"]

config:
  - changed-files:
      - any-glob-to-any-file:
          - "*.json"
          - "*.js"
          - "*.mjs"
          - "*.ts"
          - "*.yml"
          - "*.yaml"

styles:
  - changed-files:
      - any-glob-to-any-file:
          - "**/*.css"
          - "**/*.scss"

docs:
  - changed-files:
      - any-glob-to-any-file:
          - "README.md"
          - "docs/**"
          - "CONTRIBUTING.md"
          - "CODE_OF_CONDUCT.md"

tests:
  - changed-files:
      - any-glob-to-any-file: ["tests/**"]
