# Auto-label pull requests based on changed files
- label: frontend
  files:
    - "src/**"
    - "public/**"

- label: ci
  files:
    - ".github/workflows/**"

- label: config
  files:
    - "*.json"
    - "*.js"
    - "*.mjs"
    - "*.ts"
    - "*.yml"
    - "*.yaml"

- label: styles
  files:
    - "**/*.css"
    - "**/*.scss"

- label: docs
  files:
    - "README.md"
    - "docs/**"
    - "CONTRIBUTING.md"
    - "CODE_OF_CONDUCT.md"

- label: tests
  files:
    - "tests/**"
