name: Bug report
description: Report a reproducible problem or regression.
labels:
  - bug
  - triage
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve the project! Please fill in as much detail as you can.
  - type: input
    id: summary
    attributes:
      label: Summary
      description: What went wrong?
      placeholder: Button on contact form never enables submit.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      description: Include code snippets, commands, and URLs if relevant.
      placeholder: |
        1. Go to …
        2. Click …
        3. Observe …
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      placeholder: I expected the form to submit successfully…
    validations:
      required: true
  - type: input
    id: environment
    attributes:
      label: Environment
      placeholder: macOS 14.6.1 · Chrome 130 · Node 22.20.0
  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant console output or add a link to a gist.
  - type: checkboxes
    id: checklist
    attributes:
      label: Checks
      options:
        - label: I have searched open issues for duplicates.
          required: true
        - label: I am willing to submit a PR with a fix.
