name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: salem

      - uses: actions/checkout@v5
        if: ${{ steps.release.outputs.release_created }}

      - name: Setup Node.js
        uses: actions/setup-node@v5
        if: ${{ steps.release.outputs.release_created }}
        with:
          node-version: "20"
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies
        if: ${{ steps.release.outputs.release_created }}
        run: npm ci

      - name: Build project
        if: ${{ steps.release.outputs.release_created }}
        run: npm run build:static

      - name: Create release artifacts
        if: ${{ steps.release.outputs.release_created }}
        run: |
          tar -czf salem-${{ steps.release.outputs.tag_name }}.tar.gz out/
          zip -r salem-${{ steps.release.outputs.tag_name }}.zip out/

      - name: Upload Release Artifacts
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} \
            salem-${{ steps.release.outputs.tag_name }}.tar.gz \
            salem-${{ steps.release.outputs.tag_name }}.zip
